services:
  db:
    build: ./mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
     # - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  perl:
    build: ./perl
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      # - ./perl:/usr/src/app
      - ./logs:/usr/src/app/logs
      - ./mysql/init.sql:/usr/src/app/init.sql
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: mydb
volumes:
  db_data:
